const js = require("@eslint/js");

const BROWSER_GLOBALS = {
  window: "readonly",
  document: "readonly",
  localStorage: "readonly",
  fetch: "readonly",
  console: "readonly",
  setTimeout: "readonly",
  setInterval: "readonly",
  clearTimeout: "readonly",
  clearInterval: "readonly",
  navigator: "readonly",
  AbortController: "readonly",
};

const EXTENSION_GLOBALS = {
  ...BROWSER_GLOBALS,
  chrome: "readonly",
};

const NODE_GLOBALS = {
  require: "readonly",
  module: "readonly",
  exports: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  process: "readonly",
  console: "readonly",
  setTimeout: "readonly",
  setInterval: "readonly",
  clearTimeout: "readonly",
  clearInterval: "readonly",
  Buffer: "readonly",
  WebSocket: "readonly",
  URL: "readonly",
};

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: NODE_GLOBALS,
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "preserve-caught-error": "off",
      "no-useless-escape": "off",
    },
  },
  {
    files: ["bridge-extension/**/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: EXTENSION_GLOBALS,
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
    },
  },
  {
    files: ["public/**/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        ...BROWSER_GLOBALS,
        URL: "readonly",
        t: "writable",
        I18n: "writable",
        LANGS: "writable",
        LANG_NAMES: "writable",
        PetMath: "writable",
        LabMath: "writable",
        BaseMath: "writable",
        UnitMath: "writable",
        VoyagerMath: "writable",
        CraftMath: "writable",
        IconMap: "writable",
        renderTabs: "writable",
        fmtK: "writable",
        fmtPct: "writable",
        barPct: "writable",
        loadLast: "writable",
        loadHistory: "writable",
        analyze: "writable",
        setAutoRefresh: "writable",
        refreshState: "writable",
        toggleDone: "writable",
        resetDone: "writable",
        sortTable: "writable",
        setUnitEmuAll: "writable",
        bumpUnitEmu: "writable",
        maxUnitEmu: "writable",
        resetUnitEmu: "writable",
        setInvFilter: "writable",
        craftUseStock: "writable",
        setLabCapsules: "writable",
        setLabEmu: "writable",
        setLabEmuLevel: "writable",
        setLabEmuSpeed: "writable",
        labEmuAllFloor: "writable",
        bumpLabEmu: "writable",
        spendLabEmu: "writable",
        resetLabEmu: "writable",
        setBaseLevel: "writable",
        bumpBaseQcEmu: "writable",
        resetBaseQcEmu: "writable",
        maxVoyPlan: "writable",
        resetVoyPlan: "writable",
        setAutoMins: "writable",
        toggleAuto: "writable",
        setTab: "writable",
        setVariant: "writable",
        // Cross-file top-level names of the classic-script GUI bundle: app.js
        // and the per-view view-*.js files share one global scope, so each of
        // them calls helpers declared in another file of the bundle.
        esc: "writable",
        jsStr: "writable",
        tableHtml: "writable",
        setTabCount: "writable",
        card: "writable",
        cardIcon: "writable",
        headIcon: "writable",
        catIcon: "writable",
        dotColor: "writable",
        matIcon: "writable",
        slotIcon: "writable",
        actIcon: "writable",
        npcIcon: "writable",
        bodyIcon: "writable",
        petIcon: "writable",
        techIcon: "writable",
        resIcon: "writable",
        actLabel: "writable",
        rarityLabel: "writable",
        statLabel: "writable",
        statCatLabel: "writable",
        npcLabel: "writable",
        gearSlotLabel: "writable",
        itemSkillLabel: "writable",
        actIdLabel: "writable",
        moduleTypeLabel: "writable",
        bodyLabel: "writable",
        techNameLabel: "writable",
        techBoostLabel: "writable",
        techDescLabel: "writable",
        materialLabel: "writable",
        moduleLabel: "writable",
        petSlotLabel: "writable",
        petBodyLabel: "writable",
        modLabel: "writable",
        catText: "writable",
        catTextFromString: "writable",
        chainGoalText: "writable",
        capTone: "writable",
        baseRateCell: "writable",
        fmtC: "writable",
        fmtN: "writable",
        fmtOutput: "writable",
        fmtH: "writable",
        fmtHours: "writable",
        render: "writable",
        renderShipItemAdvisor: "writable",
        renderGear: "writable",
        renderInstalls: "writable",
        renderProjection: "writable",
        renderMerges: "writable",
        renderContextTotals: "writable",
        renderOverrideLosses: "writable",
        renderUnits: "writable",
        renderTech: "writable",
        calcQcGap: "writable",
        renderPets: "writable",
        simPet: "writable",
        renderInventory: "writable",
        renderCrafting: "writable",
        renderLab: "writable",
        labShortfallCount: "writable",
        renderBase: "writable",
        baseShortfallCount: "writable",
        renderVoyager: "writable",
        computeInstallKeySet: "writable",
        computeMergeKeySet: "writable",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-redeclare": "off",
    },
  },
  // public/app.js and the per-view public/view-*.js scripts declare their
  // GUI handlers as top-level functions that the page wires up through
  // onclick="..." strings inside dynamically generated HTML -- invisible to
  // static analysis, so no-unused-vars fires on every one of them. Dead
  // handlers are enforced for real by the dead-handler check in
  // check-page.js (run via npm run check), so the rule is turned off for
  // these GUI scripts only and every other rule stays as it is.
  {
    files: ["public/app.js", "public/view-*.js"],
    rules: {
      "no-unused-vars": "off",
    },
  },
  {
    files: ["test/**/*.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
      },
    },
  },
  {
    ignores: ["bridge-extension/page.js", "snapshots/**", "*.log", "node_modules/**"],
  },
];
