// Generates bridge-extension/page.js from lib/cdp.js's READ_ALL so the
// browser bridge and the DevTools path read the game with one and the same
// expression. Run after editing READ_ALL:  node bridge-extension/build.js
// test/bridge.test.js fails when the checked-in page.js is out of date.
"use strict";
const fs = require("fs");
const path = require("path");
const { READ_ALL } = require("../lib/cdp.js");

function render() {
  return [
    "// GENERATED by bridge-extension/build.js from lib/cdp.js READ_ALL. Do not edit.",
    "// Runs in the game page's own JS world (manifest world: MAIN) so it can reach",
    "// the Vue app and its Pinia stores. content.js asks for a read through",
    "// window.postMessage and gets the READ_ALL result back the same way.",
    "//",
    "// Re-injection safe: a reload of the extension injects this file again into",
    "// a game tab that is still open, and a listener from the previous injection",
    "// keeps living in the page. So the reader is stored on window and replaced",
    "// by every injection, while the message listener is registered once and",
    "// always calls the newest reader. The request type is 'read2': listeners",
    "// from before this scheme answered 'read' and are never triggered again.",
    "(() => {",
    "  const readAll = () => (",
    READ_ALL.split("\n").map(l => "    " + l).join("\n"),
    "  );",
    "  window.__soAdvisorReadAll = readAll;",
    "  if (window.__soAdvisorListenerV2) return;",
    "  window.__soAdvisorListenerV2 = true;",
    "  window.addEventListener('message', (ev) => {",
    "    if (ev.source !== window || !ev.data || ev.data.__soAdvisor !== 'read2') return;",
    "    let state;",
    "    try { state = window.__soAdvisorReadAll(); } catch (e) { state = { error: e && e.message ? e.message : String(e) }; }",
    "    window.postMessage({ __soAdvisor: 'state', nonce: ev.data.nonce, state }, '*');",
    "  });",
    "})();",
    "",
  ].join("\n");
}

const OUT = path.join(__dirname, "page.js");
if (require.main === module) {
  fs.writeFileSync(OUT, render());
  console.log("wrote " + OUT);
}
module.exports = { render, OUT };
