// GENERATED by bridge-extension/build.js from lib/cdp.js READ_ALL. Do not edit.
// Runs in the game page's own JS world (manifest world: MAIN) so it can reach
// the Vue app and its Pinia stores. content.js asks for a read through
// window.postMessage and gets the READ_ALL result back the same way.
(() => {
  const readAll = () => (
    (() => {
      const el = [...document.querySelectorAll('*')].find(e => e.__vue_app__);
      if (!el) return { error: 'no vue app' };
      const pinia = el.__vue_app__.config.globalProperties.$pinia;
      const get = (id) => {
        const s = [...pinia._s.entries()].find(([k]) => k === id);
        return s ? JSON.parse(JSON.stringify(s[1].$state)) : null;
      };
      const ship = get('ShipStore');
      const cats = get('CatalystStore');
      const craft = get('CraftStore');
      const cur = get('CurrencyStore');
      const user = get('UserStore');
      const sq = get('squadronStore');
      const petsS = get('PetsStore');
      const prem = get('PremiumStore');
      const mat = get('MaterialsStore');
      const voy = get('Voyager');
      const battleS = get('BattleStore');
      const gatherS = get('GatherStore');
      const exploreS = get('ExploreStore');
      const gboosts = get('GlobalBoostsStore');
      const lab = get('LaboratoryStore');
      const baseS = get('BaseBuildingStore');
      const gameS = get('GameStore');
      const dq = get('DailyQuestsStore');
      if (!ship || !cats) return { error: 'missing stores' };
      const p = user && user.player ? user.player : null;
      // Self-healing price listener: the game's trainer pages request
      // getNextDroidPrice / getNextClonePrice when opened; responses arrive on
      // the event bus. Cache them so the advisor can read the current prices.
      let prices = {};
      try {
        if (!window.__priceCacheInstalled) {
          const gp = el.__vue_app__.config.globalProperties;
          window.__priceCache = {};
          window.__priceCacheInstalled = true;
          gp.$eventBus.$on('socketMessage', (msg) => {
            try {
              const s = JSON.stringify(msg);
              if (s.includes('getNextDroidPrice')) window.__priceCache.droid = msg.value !== undefined ? msg.value : undefined;
              if (s.includes('getNextClonePrice')) window.__priceCache.clone = msg.value !== undefined ? msg.value : undefined;
            } catch (e) {}
          });
        }
        prices = window.__priceCache || {};
      } catch (e) { prices = {}; }
      return JSON.stringify({
        ship: {
          weapon_slot: ship.weapon_slot, shield_slot: ship.shield_slot,
          engine_slot: ship.engine_slot, sensors_slot: ship.sensors_slot,
          laser_slot: ship.laser_slot, probes_slot: ship.probes_slot,
        },
        catalysts: cats.catalysts || [],
        craft: {
          crafting_level: craft ? craft.crafting_level : 1,
          crafting_current_xp: craft ? craft.crafting_current_xp : 0,
          crafting_target_xp: craft ? craft.crafting_target_xp : 0,
        },
        dust: cur ? cur.cosmic_dust : 0,
        catalyst_parts: cur ? cur.catalyst_parts : 0,
        quantum_cores: cur ? cur.quantum_cores : 0,
        credits: cur ? cur.credits : 0,
        commonResources: cur ? {
          copper: cur.copper, gold: cur.gold, platinum: cur.platinum, silver: cur.silver,
          carbon: cur.carbon, nitrogen: cur.nitrogen, sulfur: cur.sulfur, water: cur.water,
          ammonia: cur.ammonia, helium: cur.helium, hydrogen: cur.hydrogen, methane: cur.methane,
          diamond: cur.diamond, emerald: cur.emerald, ruby: cur.ruby, sapphire: cur.sapphire,
        } : null,
        // Rare gathering currencies consumed by the lab (Circuit Integration
        // Facility, Energetic Fusion Center).
        rareCurrencies: cur ? {
          silicon: cur.silicon, cobalt: cur.cobalt, argon: cur.argon, dark_matter: cur.dark_matter,
        } : null,
        pets: petsS ? {
          pets: petsS.pets || [],
          petSlots: petsS.petSlots || [],
          premiumActive: prem ? !!prem.active : false,
          petFood: (mat && mat.materialsList)
            ? (((mat.materialsList.filter(function (x) { return x.item && x.item.name === 'pet food'; })[0]) || {}).quantity || 0)
            : 0,
        } : null,
        droids: p && p.droids ? p.droids : [],
        prices: { droid: prices.droid, clone: prices.clone },
        blueprints: (craft && craft.blueprints) ? craft.blueprints.map(function (b) {
          const item = b.item || {};
          return {
            name: item.name, rarity: item.rarity, category_type: item.category_type,
            currency_use: item.currency_use || [], material_use: item.material_use || [],
            scraps_use: item.scraps_use, charges: item.charges,
            quantity: b.quantity, locked: !!item.locked, enhanced: !!item.enhanced,
          };
        }) : [],
        materials: (mat && mat.materialsList) ? mat.materialsList.map(function (m) {
          return { name: m.item && m.item.name, quantity: m.quantity };
        }) : [],
        // timer = seconds of travel time bought off the 1800 s base (0..1200),
        // reward_bonus = +% dust/credits per discovery; both feed the upgrade
        // emulator (lib/voyager.js).
        // Every scalar field of the store is copied (the queue and planning
        // lists are left out), so a field the advisor learns to use later is
        // already in old snapshots and needs no reader change.
        voyager: voy ? Object.assign(
          Object.fromEntries(Object.entries(voy).filter(function (kv) { return kv[1] === null || typeof kv[1] !== 'object'; })),
          {
            max_fuel: voy.max_fuel, max_jumps: voy.max_jumps, current_fuel: voy.current_fuel,
            timer: voy.timer || 0, reward_bonus: voy.reward_bonus || 0,
          }) : null,
        // Laboratory: live building chain (inputs, per-unit input amount,
        // output, base timer, level), the running queues, and the queue-slot
        // pool (4 standard, 6 premium, plus purchased extra slots).
        lab: lab ? {
          buildings: (lab.buildings || []).map(function (b) {
            return {
              building: b.building, level: b.level || 0,
              currency_use: b.currency_use || [], material_use: b.material_use || [],
              produce: b.produce || [], input: b.input, output: b.output || 1, timer: b.timer,
            };
          }),
          queue: lab.labQueue || [],
          queueSlots: ((prem && prem.active) ? 6 : 4) + ((user && user.additionalQueueSlots) || 0),
        } : null,
        // Base building (null until a base is founded) and the base-tier lab
        // buildings (Aeroforge etc.; the list and nextBaseCost only populate
        // after the in-game Laboratory panel has been opened once).
        base: baseS && baseS.base ? baseS.base : null,
        baseLab: {
          buildings: (lab && Array.isArray(lab.base)) ? lab.base.map(function (b) {
            return {
              building: b.building, level: b.level || 0,
              currency_use: b.currency_use || [], material_use: b.material_use || [],
              produce: b.produce || [], input: b.input, output: b.output || 1, timer: b.timer,
            };
          }) : [],
          nextBaseCost: lab ? (lab.nextBaseCost || 0) : 0,
          nextBuildingCost: lab ? (lab.nextBuildingCost || 0) : 0,
        },
        // Lifetime credits earned + registration time: the base upkeep formula
        // divides one by the other.
        account: {
          registered: user ? (user.registered || 0) : 0,
          lifetimeCredits: (p && p.statistics && p.statistics.credits && p.statistics.credits.$numberDecimal !== undefined)
            ? Number(p.statistics.credits.$numberDecimal) : ((p && p.statistics && typeof p.statistics.credits === 'number') ? p.statistics.credits : 0),
        },
        // Daily quests: how many are claimed today (feeds the upkeep coverage
        // estimate) vs merely completed but unclaimed.
        dailyQuests: dq && Array.isArray(dq.quests) ? { claimed: dq.quests.filter(function (q) { return q && q.claimed; }).length, completed: dq.quests.filter(function (q) { return q && q.completed; }).length, total: dq.quests.length } : null,
        currentSystem: (exploreS && exploreS.currentSystem) ? {
          name: exploreS.currentSystem.name, star: exploreS.currentSystem.star,
          bodies: (exploreS.currentSystem.bodies || []).map(function (b) { return b.type; }),
        } : null,
        bookmarks: (exploreS && Array.isArray(exploreS.bookmarks)) ? exploreS.bookmarks
          .filter(function (b) { return b && b.system; })
          .map(function (b) {
            return { name: b.system.name, star: b.system.star, bodies: (b.system.bodies || []).map(function (x) { return x.type; }) };
          }) : [],
        gameVersion: gameS ? (gameS.patchVersion || null) : null,
        // Basename of the client bundle the page actually loaded: the formula
        // provenance check compares it with the bundle the constants came from.
        clientBundle: (function () {
          try {
            var srcs = Array.prototype.map.call(document.scripts, function (sc) { return sc.src || ""; });
            var hit = srcs.filter(function (u) { return /index-[A-Za-z0-9_-]+.js/.test(u); })[0];
            return hit ? hit.split("/").pop() : null;
          } catch (e) { return null; }
        })(),
        skillLevels: {
          battling: battleS ? battleS.battling_level : null,
          gathering: gatherS ? gatherS.gathering_level : null,
          exploring: exploreS ? exploreS.exploring_level : null,
        },
        ssBattlingBoost: (sq && typeof sq.effectiveSSBattlingBoost === "number") ? sq.effectiveSSBattlingBoost : 0,
        // squadronStore is not always populated. Substituting 0 silently strips
        // the squadron multiplier from every battle number, which looks exactly
        // like a real collapse -- and used to be written to history as one.
        ssBattlingBoostKnown: !!(sq && typeof sq.effectiveSSBattlingBoost === "number"),
        // Last gathering action: how many droids came back alive (per-droid
        // statistics on the last reward), to sanity-check the dodge formula.
        gatherLast: (gatherS && gatherS.lastReward && Array.isArray(gatherS.lastReward.statistics)) ? {
          alive: gatherS.lastReward.statistics.filter(function (d) { return d && d.alive; }).length,
          total: gatherS.lastReward.statistics.length,
        } : null,
        // Global boost timers (epoch seconds) by boost name, e.g. Cooldown/XP/
        // Income/'Drop chance'. Tier and bonus are derived from remaining time.
        globalBoosts: (gboosts && gboosts.currentBoosts) ? Object.fromEntries(
          gboosts.currentBoosts
            .filter(function (b) { return b && b.boost && b.boost.name; })
            .map(function (b) { return [b.boost.name, b.timer || 0]; })
        ) : {},
        stateReadAt: Math.floor(Date.now() / 1000),
        player: p ? {
          stats: p.stats || null,
          skills: p.skills || null,
          clones: (p.clones || []).map(c => ({
            name: c.name, critical_chance: c.critical_chance,
            critical_damage: c.critical_damage, dual_shot: c.dual_shot,
          })),
        } : null,
      });
    })()
  );
  window.addEventListener('message', (ev) => {
    if (ev.source !== window || !ev.data || ev.data.__soAdvisor !== 'read') return;
    let state;
    try { state = readAll(); } catch (e) { state = { error: e && e.message ? e.message : String(e) }; }
    window.postMessage({ __soAdvisor: 'state', nonce: ev.data.nonce, state }, '*');
  });
})();
